[package]
name = "logai-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
serde ={ version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4", "serde"] }

regex = "1.5"